[package]
name = "dashboard"
version = "0.2.0"
edition = "2021"

# Optimize for size in release builds
[profile.release]
opt-level = "z"   # Optimize for size
lto = true        # Enable link-time optimization
codegen-units = 1 # Better optimization
panic = "abort"   # Smaller binary size
strip = true      # Strip debug symbols


[dependencies]
reqwest = { version = "0.12.15", features = [
  "json",
  "rustls-tls",
], default-features = false }
chrono = { version = "0.4.41", features = ["serde"] }
icalendar = { version = "0.16.13", features = [
  "chrono-tz",
  "serde",
  "serde_json",
  "parser",
] }
serde = "1.0.219"
tokio = { version = "1.45.0", features = [
  "macros",
  "rt-multi-thread",
  "signal",
] }
axum = { version = "0.8.4", features = ["macros", "tokio"] }
tower-http = { version = "0.6.4", features = ["fs"] }
log = { version = "0.4.27", default-features = false }
env_logger = { version = "0.11.8", features = ["auto-color"] }
clap = "4.5.32"
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.4.0"
serde_json = "1.0.140"
thiserror = "2.0.12"
[dependencies.config]
version = "0.15.16"
features = ["toml"]
