[package]
name = "dashboard"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.14"
chrono = { version = "0.4.40", features = ["serde"] }
icalendar = { version = "0.16.13", features = [
  "chrono-tz",
  "serde",
  "serde_json",
  "parser",
] }
serde = "1.0.219"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread", "signal"] }
axum = { version = "0.8.1", features = ["tokio"] }
tower-http = { version = "0.6.2", features = ["fs"] }
log = { version = "0.4.26", default-features = false }
env_logger = { version = "0.11.7", features = ["auto-color"] }
config = { version = "0.15.11", features = ["toml"] }
clap = "4.5.32"
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.4.0"
