[platformio]
default_envs = espink-v2

[env:espink-v2]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    256dpi/MQTT@2.5.3
    adafruit/Adafruit SHT4x Library@1.0.5
build_flags =
    -D ESPINK_V2
